-- Crear bases de datos para cada microservicio
CREATE DATABASE IF NOT EXISTS autenticacion_db;
CREATE DATABASE IF NOT EXISTS usuario_db;
CREATE DATABASE IF NOT EXISTS autor_db;
CREATE DATABASE IF NOT EXISTS categoria_db;
CREATE DATABASE IF NOT EXISTS libro_db;
CREATE DATABASE IF NOT EXISTS inventario_db;
CREATE DATABASE IF NOT EXISTS prestamo_db;
CREATE DATABASE IF NOT EXISTS reserva_db;
CREATE DATABASE IF NOT EXISTS multa_db;
CREATE DATABASE IF NOT EXISTS reporte_db;

-- Otorgar permisos
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;